pub const VOXEL_SIZE: f32 = 1.0;
pub const TERRAIN_CHUNK_SIZE: u32 = 64;
pub const PADDED_TERRAIN_CHUNK_SIZE: u32 = TERRAIN_CHUNK_SIZE + 2;
pub const TERRAIN_CHUNK_LENGTH: f32 = TERRAIN_CHUNK_SIZE as f32 * VOXEL_SIZE;